server:
  port: 8764

spring:
  application:
    name: service-email
eureka:
  instance:
    hostname: 192.168.1.105
    preferIpAddress: true
#    instance-id: window:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
