server:
  port: 8762

spring:
  application:
    name: serviceCall

feign.hystrix.enabled: false
#feign:
 # hystrix:
  #  enabled:  false
  #client:
  #  config:
  #    default:           #服务名，填写default为所有服务
  #      execution:
  #        timeout:
  #          enabled: false
  #      connectTimeout: 5000
  #      readTimeout: 12000
#  ribbon:    
#    maxAutoRetries: 10
#    ReadTimeout: 60000    
#    ConnectTimeout: 60000

eureka:
  instance:
    hostname: 192.168.1.105
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
  client:
    registry-fetch-interval-seconds: 5 #客户端拉取注册中心的服务列表
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
