  redis:
    host: 192.168.1.104
    port: 6379
#    password: 
    database: 0
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: SERVICEHI
        uri: http://192.168.1.104:8762
#        uri: lb://SERVICEHI
        order: 0
        predicates:
          - Path=/zhuxueshi/**
        filters:
          - StripPrefix=1
          - RequestTime=true
          # 熔断降级配置
          - name: Hystrix
            args:
              name : default
              fallbackUri: 'forward:/defaultfallback'
          #限流处理
          - name: RequestRateLimiter
            args:
              key-resolver: '#{@uritLimit}'
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 12
              
# hystrix 信号量隔离，3秒后自动超时
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
#  shareSecurityContext: true
