server:
  port: 8765

spring:
  application:
    name: service-email
eureka:
  instance:
    hostname: 172.18.184.216
    preferIpAddress: true
    instance-id: window:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
